import { useState } from 'react';
import type { User } from 'firebase/auth';
import type { AdminProfile } from '../../utils/adminControlPlane';
import { saveAdminGoogleMapsCredentials, testAdminGoogleMapsConnection, type AdminGoogleMapsCredentialStatus, type AdminIntegrationProviderState } from '../../utils/adminIntegrationReadiness';

const STATE_LABEL: Record<AdminIntegrationProviderState, string> = { configured: 'Configurado', partial: 'Atenção', 'not-configured': 'Não configurado', 'contract-only': 'Contrato preparado' };

export default function AdminGoogleMapsProviderCard({ authenticatedUser, profile, providerState, vaultReady, onChanged }: { authenticatedUser: User; profile: AdminProfile; providerState?: AdminIntegrationProviderState; vaultReady: boolean; onChanged: () => Promise<void>; }) {
  const [apiKey,setApiKey]=useState(''); const [saving,setSaving]=useState(false); const [testing,setTesting]=useState(false); const [status,setStatus]=useState<AdminGoogleMapsCredentialStatus|null>(null); const [message,setMessage]=useState('');
  const save=async()=>{if(!apiKey.trim()){setMessage('Informe a API Key do Google Maps antes de salvar.');return;}setSaving(true);setMessage('');try{const next=await saveAdminGoogleMapsCredentials(authenticatedUser,profile,{apiKey});setStatus(next);setApiKey('');setMessage('API Key protegida no cofre. O valor completo não será exibido novamente.');await onChanged();}catch(caught){setMessage(caught instanceof Error?caught.message:'Não foi possível salvar a API Key.');}finally{setSaving(false);}};
  const test=async()=>{setTesting(true);setMessage('');try{const result=await testAdminGoogleMapsConnection(authenticatedUser,profile);setStatus(result.credential);setMessage(result.ok?'Google Maps Geocoding validado pelo backend.':`A conexão não foi validada (${result.code||'erro desconhecido'}).`);await onChanged();}catch(caught){setMessage(caught instanceof Error?caught.message:'Não foi possível testar o Google Maps.');}finally{setTesting(false);}};
  return <article className="mt-5 rounded-2xl border border-emerald-500/20 bg-emerald-500/5 p-4"><div className="flex flex-col gap-2 sm:flex-row sm:items-start sm:justify-between"><div><span className="text-[9px] font-black uppercase tracking-wider text-emerald-400">Google Maps Platform · produção</span><h3 className="mt-1 text-sm font-black text-white">Geocodificação e destino canônico</h3><p className="mt-1 max-w-2xl text-[10px] leading-relaxed text-slate-500">A chave fica no backend e resolve endereços do checkout em coordenadas e Place ID. Abrir o Maps por URL continua independente desta chave.</p></div><span className="rounded-full border border-slate-700 px-2.5 py-1 text-[9px] font-black uppercase text-slate-300">{providerState?STATE_LABEL[providerState]:'Aguardando leitura'}</span></div><label className="mt-4 block text-[10px] font-bold text-slate-400">Google Maps API Key<input type="password" autoComplete="off" value={apiKey} onChange={event=>setApiKey(event.target.value)} placeholder={status?.apiKeyLast4?`Salva ·••••${status.apiKeyLast4}`:'Cole a API Key do projeto Google Cloud'} className="mt-1 w-full rounded-xl border border-slate-700 bg-slate-950/70 px-3 py-2.5 text-xs text-white outline-none focus:border-emerald-500"/></label><div className="mt-4 flex flex-wrap gap-2"><button type="button" onClick={()=>void save()} disabled={saving||testing||!vaultReady} className="rounded-xl bg-emerald-500 px-4 py-2 text-[10px] font-black uppercase tracking-wider text-slate-950 disabled:opacity-40">{saving?'Salvando…':'Salvar no cofre'}</button><button type="button" onClick={()=>void test()} disabled={saving||testing||providerState==='not-configured'} className="rounded-xl border border-slate-700 bg-slate-900 px-4 py-2 text-[10px] font-black uppercase tracking-wider text-slate-200 disabled:opacity-40">{testing?'Testando…':'Testar Geocoding'}</button></div>{message&&<p className="mt-3 rounded-xl border border-slate-800 bg-slate-950/50 p-3 text-[10px] leading-relaxed text-slate-300" aria-live="polite">{message}</p>}</article>;
}