import { useEffect, useState } from 'react';
import { CircleAlert, CircleCheck, FileCheck2, KeyRound, LockKeyhole, PlugZap } from 'lucide-react';
import type { User } from 'firebase/auth';
import type { AdminProfile } from '../../utils/adminControlPlane';
import { loadAdminFocusCredentialStatus, saveAdminFocusCredential, testAdminFocusConnection, type AdminFocusCredentialStatus } from '../../utils/adminFocusProvider';

export interface AdminFiscalProviderReadinessView { providerId: 'focus-nfe'; providerReady: boolean; storeReady: boolean; productionTrafficAllowed: false; blockers: string[]; }
type FiscalAdminIdentity = { user: Pick<User, 'getIdToken'>; profile: Pick<AdminProfile, 'role' | 'status'> };
const blockerLabel = (value: string): string => ({ provider_not_ready: 'Provider global ainda não está pronto', store_not_production_authorized: 'Nenhuma loja selecionada está autorizada para produção' }[value] ?? value);

export default function AdminFiscalProviderCard({ readiness, user, profile }: { readiness?: AdminFiscalProviderReadinessView | null; user?: Pick<User, 'getIdToken'>; profile?: Pick<AdminProfile, 'role' | 'status'>; }) {
  const providerReady = readiness?.providerReady === true; const storeReady = readiness?.storeReady === true;
  const identity: FiscalAdminIdentity | null = user && profile ? { user, profile } : null;
  const [credential, setCredential] = useState<AdminFocusCredentialStatus | null>(null); const [token, setToken] = useState(''); const [busy, setBusy] = useState<'load'|'save'|'test'|null>(identity ? 'load' : null); const [feedback, setFeedback] = useState(identity ? '' : 'Controles de credencial aguardando vínculo seguro com a identidade do Super Admin.');
  useEffect(() => { if (!identity) return; let active = true; setBusy('load'); void loadAdminFocusCredentialStatus(identity.user, identity.profile).then(value => { if (active) setCredential(value); }).catch(error => { if (active) setFeedback(error instanceof Error ? error.message : 'Não foi possível consultar a Focus.'); }).finally(() => { if (active) setBusy(null); }); return () => { active = false; }; }, [user, profile]);
  const save = async () => { if (!identity || !token.trim() || busy) return; setBusy('save'); setFeedback(''); try { setCredential(await saveAdminFocusCredential(identity.user, identity.profile, token)); setToken(''); setFeedback('Credencial principal armazenada no cofre. Agora teste a conexão.'); } catch (error) { setFeedback(error instanceof Error ? error.message : 'Falha ao salvar a credencial.'); } finally { setBusy(null); } };
  const test = async () => { if (!identity || busy) return; setBusy('test'); setFeedback(''); try { const result = await testAdminFocusConnection(identity.user, identity.profile); setCredential(result.credential); setFeedback(result.ok ? 'Conexão autenticada com a Focus.' : `A Focus não validou a conexão (${result.code || 'erro'}).`); } catch (error) { setFeedback(error instanceof Error ? error.message : 'Falha ao testar a Focus.'); } finally { setBusy(null); } };

  return <article className="mt-5 rounded-2xl border border-violet-500/20 bg-violet-500/5 p-4">
    <div className="flex flex-col gap-2 sm:flex-row sm:items-start sm:justify-between"><div><span className="text-[9px] font-black uppercase tracking-wider text-violet-400">Kyrub Fiscal · fornecedor gerenciado</span><h3 className="mt-1 text-sm font-black text-white">Focus NFe · infraestrutura fiscal</h3><p className="mt-1 max-w-2xl text-[10px] leading-relaxed text-slate-500">A credencial principal pertence à plataforma Kyrub. Tokens dos emitentes permanecem exclusivamente no backstage.</p></div><span className="inline-flex items-center gap-1.5 rounded-full border border-slate-700 px-2.5 py-1 text-[9px] font-black uppercase text-slate-300">{providerReady ? <CircleCheck className="h-3.5 w-3.5 text-emerald-400" /> : <CircleAlert className="h-3.5 w-3.5 text-amber-400" />}{providerReady ? 'Provider pronto' : 'Provider não pronto'}</span></div>
    <div className="mt-4 grid gap-3 sm:grid-cols-3"><div className="rounded-xl border border-slate-800 bg-slate-950/45 p-3"><p className="text-[9px] font-black uppercase tracking-wider text-slate-500">Credencial global</p><p className="mt-1 text-xs font-bold text-slate-200">{busy === 'load' ? 'Consultando...' : credential?.configured ? `Configurada${credential.tokenLast4 ? ` · ••••${credential.tokenLast4}` : ''}` : 'Não configurada'}</p></div><div className="rounded-xl border border-slate-800 bg-slate-950/45 p-3"><p className="text-[9px] font-black uppercase tracking-wider text-slate-500">Loja fiscal</p><p className="mt-1 text-xs font-bold text-slate-200">{storeReady ? 'Produção autorizada' : 'Não autorizada'}</p></div><div className="rounded-xl border border-slate-800 bg-slate-950/45 p-3"><p className="text-[9px] font-black uppercase tracking-wider text-slate-500">Tráfego produtivo</p><p className="mt-1 inline-flex items-center gap-1.5 text-xs font-bold text-slate-200"><LockKeyhole className="h-3.5 w-3.5 text-amber-400" /> Bloqueado até autorização</p></div></div>
    <div className="mt-4 rounded-xl border border-violet-500/20 bg-slate-950/45 p-3"><div className="flex items-center gap-2"><KeyRound className="h-4 w-4 text-violet-300"/><p className="text-[9px] font-black uppercase tracking-wider text-violet-300">Token principal Focus · produção</p></div><div className="mt-3 flex flex-col gap-2 sm:flex-row"><input type="password" autoComplete="new-password" value={token} onChange={event => setToken(event.target.value)} disabled={!identity} placeholder={credential?.configured ? 'Informe somente para substituir a credencial' : 'Cole o token principal da plataforma'} className="min-h-11 flex-1 rounded-xl border border-slate-700 bg-slate-950 px-3 text-[11px] text-white outline-none focus:border-violet-500/60 disabled:opacity-50"/><button type="button" onClick={() => void save()} disabled={!identity || busy !== null || !token.trim()} className="min-h-11 rounded-xl bg-violet-600 px-4 text-[10px] font-black uppercase text-white disabled:opacity-50">{busy === 'save' ? 'Salvando...' : 'Salvar no cofre'}</button><button type="button" onClick={() => void test()} disabled={!identity || busy !== null || !credential?.configured} className="min-h-11 rounded-xl border border-violet-500/30 px-4 text-[10px] font-black uppercase text-violet-200 disabled:opacity-50"><span className="inline-flex items-center gap-1.5"><PlugZap className="h-3.5 w-3.5"/>{busy === 'test' ? 'Testando...' : 'Testar conexão'}</span></button></div>{feedback && <p className="mt-2 text-[10px] text-slate-300" role="status">{feedback}</p>}<p className="mt-2 text-[9px] leading-relaxed text-slate-600">O token é enviado diretamente ao backend e armazenado no cofre. Depois de salvo, o valor completo não volta para esta tela.</p></div>
    {(readiness?.blockers.length ?? 0) > 0 && <div className="mt-3 rounded-xl border border-amber-500/20 bg-amber-500/5 p-3"><p className="text-[9px] font-black uppercase tracking-wider text-amber-300">Pendências de readiness</p><ul className="mt-2 space-y-1 text-[10px] text-slate-400">{readiness?.blockers.map(blocker => <li key={blocker}>• {blockerLabel(blocker)}</li>)}</ul></div>}
    <div className="mt-3 flex items-start gap-2 rounded-xl border border-slate-800 bg-slate-950/35 p-3 text-[10px] leading-relaxed text-slate-500"><FileCheck2 className="mt-0.5 h-3.5 w-3.5 shrink-0 text-violet-300"/>A configuração deste card administra apenas o fornecedor global. Ela não autoriza nenhuma loja a emitir automaticamente.</div>
  </article>;
}