import { useCallback, useEffect, useState } from 'react';
import { RefreshCw, ShieldAlert, Trash2 } from 'lucide-react';
import type { User } from 'firebase/auth';
import type { AdminProfile } from '../../utils/adminControlPlane';

interface ModerationPost { id: string; authorId: string; authorName: string; content: string; publicationType: 'feed' | 'status'; visibility: string; createdAtIso: string; mediaUrls: string[]; }
const request = async (user: User, transport: string, init?: RequestInit) => {
  const token = await user.getIdToken();
  const response = await fetch(`/api/admin/operations/health?transport=${transport}`, { ...init, headers: { 'content-type': 'application/json', authorization: `Bearer ${token}`, ...(init?.headers ?? {}) } });
  const body = await response.json().catch(() => ({})) as Record<string, unknown>;
  if (!response.ok) throw new Error(typeof body.error === 'string' ? body.error : 'Operação administrativa não concluída.');
  return body;
};
export default function AdminSocialModerationWorkspace({ authenticatedUser, profile }: { authenticatedUser: User; profile: AdminProfile }) {
  const [posts,setPosts]=useState<ModerationPost[]>([]); const [busy,setBusy]=useState(false); const [error,setError]=useState('');
  const load=useCallback(async()=>{setBusy(true);setError('');try{const body=await request(authenticatedUser,'social-moderation-list');setPosts(Array.isArray(body.posts)?body.posts as ModerationPost[]:[]);}catch(e){setError(e instanceof Error?e.message:'Falha ao carregar publicações.');}finally{setBusy(false);}},[authenticatedUser]);
  useEffect(()=>{void load();},[load]);
  const remove=async(post:ModerationPost)=>{const reason=window.prompt(`Motivo da remoção de “${post.content.slice(0,80) || post.id}”:`,'Conteúdo de teste');if(!reason)return;if(!window.confirm('Remover esta publicação e suas interações relacionadas? Esta ação não pode ser desfeita.'))return;setBusy(true);setError('');try{await request(authenticatedUser,'social-moderation-remove',{method:'POST',body:JSON.stringify({postId:post.id,reason})});setPosts(current=>current.filter(item=>item.id!==post.id));}catch(e){setError(e instanceof Error?e.message:'Falha ao remover publicação.');}finally{setBusy(false);}};
  return <section id="admin-social-moderation" className="space-y-3"><div className="flex items-center justify-between gap-3"><div><h4 className="text-xs font-black text-white">Moderação da Praça</h4><p className="mt-1 text-[9px] text-slate-500">Publicações reais do feed. Remoções são executadas no servidor e auditadas.</p></div><button type="button" onClick={()=>void load()} disabled={busy} className="rounded-xl border border-slate-700 p-2 text-slate-300" aria-label="Atualizar moderação"><RefreshCw className={`h-4 w-4 ${busy?'animate-spin':''}`}/></button></div>{error&&<div className="rounded-xl border border-red-500/20 bg-red-500/10 p-3 text-[10px] text-red-200">{error}</div>}<div className="space-y-2">{posts.map(post=><article key={post.id} className="rounded-2xl border border-slate-800 bg-slate-950/50 p-3"><div className="flex items-start justify-between gap-3"><div className="min-w-0"><div className="flex items-center gap-2"><ShieldAlert className="h-3.5 w-3.5 text-amber-400"/><strong className="truncate text-[10px] text-white">{post.authorName}</strong><span className="text-[8px] uppercase text-slate-600">{post.publicationType}</span></div><p className="mt-2 whitespace-pre-wrap text-[10px] leading-relaxed text-slate-300">{post.content||'(sem texto)'}</p>{post.mediaUrls?.length>0&&<div className="mt-2 flex gap-2 overflow-x-auto">{post.mediaUrls.map((url,index)=><img key={`${post.id}-${index}`} src={url} alt="Mídia da publicação moderada" className="h-20 w-20 rounded-lg border border-slate-800 object-cover" loading="lazy"/>)}</div>}<p className="mt-2 font-mono text-[8px] text-slate-600">{post.id} · {post.createdAtIso||'data indisponível'}</p></div><button type="button" onClick={()=>void remove(post)} disabled={busy} className="shrink-0 rounded-xl border border-red-500/20 bg-red-500/10 p-2 text-red-300" title="Remover publicação"><Trash2 className="h-4 w-4"/></button></div></article>)}{!busy&&posts.length===0&&<p className="py-5 text-center text-[10px] text-slate-600">Nenhuma publicação encontrada.</p>}</div><p className="text-[8px] text-slate-600">Acesso: {profile.role}. A listagem é limitada às 100 publicações mais recentes.</p></section>;
}
