import { useState } from 'react';
import type { User } from 'firebase/auth';
import type { AdminProfile } from '../../utils/adminControlPlane';
import { saveAdminMercadoPagoCredentials, testAdminMercadoPagoConnection, type AdminIntegrationProviderState, type AdminMercadoPagoCredentialStatus } from '../../utils/adminIntegrationReadiness';

const STATE_LABEL: Record<AdminIntegrationProviderState, string> = { configured: 'Configurado', partial: 'Atenção', 'not-configured': 'Não configurado', 'contract-only': 'Contrato preparado' };

export default function AdminMercadoPagoProviderCard({ authenticatedUser, profile, providerState, vaultReady, onChanged }: { authenticatedUser: User; profile: AdminProfile; providerState?: AdminIntegrationProviderState; vaultReady: boolean; onChanged: () => Promise<void>; }) {
  const [accessToken,setAccessToken]=useState(''); const [webhookSecret,setWebhookSecret]=useState(''); const [saving,setSaving]=useState(false); const [testing,setTesting]=useState(false); const [status,setStatus]=useState<AdminMercadoPagoCredentialStatus|null>(null); const [message,setMessage]=useState('');
  const save=async()=>{if(!accessToken.trim()){setMessage('Informe o Access Token antes de salvar.');return;}setSaving(true);setMessage('');try{const next=await saveAdminMercadoPagoCredentials(authenticatedUser,profile,{accessToken,webhookSecret});setStatus(next);setAccessToken('');setWebhookSecret('');setMessage('Credencial protegida no cofre. O valor completo não será exibido novamente.');await onChanged();}catch(caught){setMessage(caught instanceof Error?caught.message:'Não foi possível salvar a credencial.');}finally{setSaving(false);}};
  const test=async()=>{setTesting(true);setMessage('');try{const result=await testAdminMercadoPagoConnection(authenticatedUser,profile);setStatus(result.credential);setMessage(result.ok?'Conexão com o Mercado Pago validada pelo backend.':`A conexão não foi validada (${result.code||'erro desconhecido'}).`);await onChanged();}catch(caught){setMessage(caught instanceof Error?caught.message:'Não foi possível testar a conexão.');}finally{setTesting(false);}};
  return <article className="mt-5 rounded-2xl border border-cyan-500/20 bg-cyan-500/5 p-4"><div className="flex flex-col gap-2 sm:flex-row sm:items-start sm:justify-between"><div><span className="text-[9px] font-black uppercase tracking-wider text-cyan-400">Mercado Pago · produção</span><h3 className="mt-1 text-sm font-black text-white">Configurar credenciais</h3><p className="mt-1 max-w-2xl text-[10px] leading-relaxed text-slate-500">Após salvar, o navegador recebe apenas metadados mascarados.</p></div><span className="rounded-full border border-slate-700 px-2.5 py-1 text-[9px] font-black uppercase text-slate-300">{providerState?STATE_LABEL[providerState]:'Aguardando leitura'}</span></div><div className="mt-4 grid gap-3 lg:grid-cols-2"><label className="text-[10px] font-bold text-slate-400">Access Token<input type="password" autoComplete="off" value={accessToken} onChange={event=>setAccessToken(event.target.value)} placeholder={status?.accessTokenLast4?`Salvo ·••••${status.accessTokenLast4}`:'Cole o Access Token'} className="mt-1 w-full rounded-xl border border-slate-700 bg-slate-950/70 px-3 py-2.5 text-xs text-white outline-none focus:border-cyan-500"/></label><label className="text-[10px] font-bold text-slate-400">Webhook Secret<input type="password" autoComplete="off" value={webhookSecret} onChange={event=>setWebhookSecret(event.target.value)} placeholder={status?.webhookSecretLast4?`Salvo ·••••${status.webhookSecretLast4}`:'Opcional nesta primeira gravação'} className="mt-1 w-full rounded-xl border border-slate-700 bg-slate-950/70 px-3 py-2.5 text-xs text-white outline-none focus:border-cyan-500"/></label></div><div className="mt-4 flex flex-wrap gap-2"><button type="button" onClick={()=>void save()} disabled={saving||testing||!vaultReady} className="rounded-xl bg-cyan-500 px-4 py-2 text-[10px] font-black uppercase tracking-wider text-slate-950 disabled:opacity-40">{saving?'Salvando…':'Salvar no cofre'}</button><button type="button" onClick={()=>void test()} disabled={saving||testing||providerState==='not-configured'} className="rounded-xl border border-slate-700 bg-slate-900 px-4 py-2 text-[10px] font-black uppercase tracking-wider text-slate-200 disabled:opacity-40">{testing?'Testando…':'Testar conexão'}</button></div>{message&&<p className="mt-3 rounded-xl border border-slate-800 bg-slate-950/50 p-3 text-[10px] leading-relaxed text-slate-300" aria-live="polite">{message}</p>}</article>;
}