import { useState } from 'react';
import { CircleCheck, FlaskConical, KeyRound, LockKeyhole, PlugZap, Store } from 'lucide-react';
import type { User } from 'firebase/auth';
import type { AdminProfile } from '../../utils/adminControlPlane';
import { loadAdminFocusIssuerCredentialStatus, saveAdminFocusIssuerCredential, testAdminFocusIssuerConnection, type AdminFocusIssuerCredentialStatus } from '../../utils/adminFocusProvider';

type Props = { user: Pick<User, 'getIdToken'>; profile: Pick<AdminProfile, 'role' | 'status'> };

export default function AdminFiscalIssuerCard({ user, profile }: Props) {
  const [storeId, setStoreId] = useState('');
  const [token, setToken] = useState('');
  const [credential, setCredential] = useState<AdminFocusIssuerCredentialStatus | null>(null);
  const [busy, setBusy] = useState<'load' | 'save' | 'test' | null>(null);
  const [feedback, setFeedback] = useState('Selecione a loja pelo ID canônico para configurar somente o ambiente de homologação.');
  const canonicalStoreId = storeId.trim();

  const load = async () => { if (!canonicalStoreId || busy) return; setBusy('load'); try { setCredential(await loadAdminFocusIssuerCredentialStatus(user, profile, canonicalStoreId)); setFeedback('Estado de homologação carregado.'); } catch (error) { setFeedback(error instanceof Error ? error.message : 'Não foi possível consultar o emitente.'); } finally { setBusy(null); } };
  const save = async () => { if (!canonicalStoreId || !token.trim() || busy) return; setBusy('save'); try { setCredential(await saveAdminFocusIssuerCredential(user, profile, canonicalStoreId, token)); setToken(''); setFeedback('Token Homologação armazenado no cofre. Agora valide a conexão.'); } catch (error) { setFeedback(error instanceof Error ? error.message : 'Não foi possível salvar o token.'); } finally { setBusy(null); } };
  const test = async () => { if (!canonicalStoreId || busy) return; setBusy('test'); try { const result = await testAdminFocusIssuerConnection(user, profile, canonicalStoreId); setFeedback(result.ok ? 'Token Homologação autenticado com a Focus.' : `A Focus não validou o token (${result.code || 'erro'}).`); setCredential(await loadAdminFocusIssuerCredentialStatus(user, profile, canonicalStoreId)); } catch (error) { setFeedback(error instanceof Error ? error.message : 'Não foi possível validar o token.'); } finally { setBusy(null); } };

  return <article className="mt-4 rounded-2xl border border-cyan-500/20 bg-cyan-500/5 p-4">
    <div className="flex flex-col gap-2 sm:flex-row sm:items-start sm:justify-between"><div><span className="text-[9px] font-black uppercase tracking-wider text-cyan-400">Kyrub Fiscal · emitente</span><h3 className="mt-1 text-sm font-black text-white">Loja / Emitente · homologação Focus</h3><p className="mt-1 max-w-2xl text-[10px] leading-relaxed text-slate-500">Credencial isolada por loja. Este fluxo não concede autorização de produção.</p></div><span className="inline-flex items-center gap-1.5 rounded-full border border-cyan-500/20 px-2.5 py-1 text-[9px] font-black uppercase text-cyan-200"><FlaskConical className="h-3.5 w-3.5"/>Homologação</span></div>
    <div className="mt-4 grid gap-3 sm:grid-cols-3"><div className="rounded-xl border border-slate-800 bg-slate-950/45 p-3"><p className="text-[9px] font-black uppercase text-slate-500">Loja</p><p className="mt-1 truncate text-xs font-bold text-slate-200">{credential?.canonicalStoreId || canonicalStoreId || 'Não selecionada'}</p></div><div className="rounded-xl border border-slate-800 bg-slate-950/45 p-3"><p className="text-[9px] font-black uppercase text-slate-500">Token homologação</p><p className="mt-1 text-xs font-bold text-slate-200">{credential?.configured ? `Configurado${credential.tokenLast4 ? ` · ••••${credential.tokenLast4}` : ''}` : 'Não configurado'}</p></div><div className="rounded-xl border border-slate-800 bg-slate-950/45 p-3"><p className="text-[9px] font-black uppercase text-slate-500">Produção</p><p className="mt-1 inline-flex items-center gap-1.5 text-xs font-bold text-slate-200"><LockKeyhole className="h-3.5 w-3.5 text-amber-400"/>Bloqueada</p></div></div>
    <div className="mt-4 rounded-xl border border-cyan-500/20 bg-slate-950/45 p-3"><div className="flex items-center gap-2"><Store className="h-4 w-4 text-cyan-300"/><p className="text-[9px] font-black uppercase tracking-wider text-cyan-300">ID canônico da loja</p></div><div className="mt-3 flex flex-col gap-2 sm:flex-row"><input value={storeId} onChange={event => { setStoreId(event.target.value); setCredential(null); }} placeholder="stores/{storeId} — informe somente o storeId" className="min-h-11 flex-1 rounded-xl border border-slate-700 bg-slate-950 px-3 text-[11px] text-white outline-none focus:border-cyan-500/60"/><button type="button" onClick={() => void load()} disabled={!canonicalStoreId || busy !== null} className="min-h-11 rounded-xl border border-cyan-500/30 px-4 text-[10px] font-black uppercase text-cyan-200 disabled:opacity-50">{busy === 'load' ? 'Consultando...' : 'Carregar loja'}</button></div></div>
    <div className="mt-3 rounded-xl border border-cyan-500/20 bg-slate-950/45 p-3"><div className="flex items-center gap-2"><KeyRound className="h-4 w-4 text-cyan-300"/><p className="text-[9px] font-black uppercase tracking-wider text-cyan-300">Token Homologação Focus</p></div><div className="mt-3 flex flex-col gap-2 sm:flex-row"><input type="password" autoComplete="new-password" value={token} onChange={event => setToken(event.target.value)} disabled={!canonicalStoreId} placeholder={credential?.configured ? 'Informe somente para substituir o token' : 'Cole o Token Homologação da empresa'} className="min-h-11 flex-1 rounded-xl border border-slate-700 bg-slate-950 px-3 text-[11px] text-white outline-none focus:border-cyan-500/60 disabled:opacity-50"/><button type="button" onClick={() => void save()} disabled={!canonicalStoreId || !token.trim() || busy !== null} className="min-h-11 rounded-xl bg-cyan-600 px-4 text-[10px] font-black uppercase text-white disabled:opacity-50">{busy === 'save' ? 'Salvando...' : 'Salvar no cofre'}</button><button type="button" onClick={() => void test()} disabled={!canonicalStoreId || !credential?.configured || busy !== null} className="min-h-11 rounded-xl border border-cyan-500/30 px-4 text-[10px] font-black uppercase text-cyan-200 disabled:opacity-50"><span className="inline-flex items-center gap-1.5"><PlugZap className="h-3.5 w-3.5"/>{busy === 'test' ? 'Validando...' : 'Validar token'}</span></button></div>{feedback && <p className="mt-2 text-[10px] text-slate-300" role="status">{feedback}</p>}{credential?.status === 'validated' && <p className="mt-2 inline-flex items-center gap-1.5 text-[10px] font-bold text-emerald-300"><CircleCheck className="h-3.5 w-3.5"/>Credencial homologada pelo probe remoto.</p>}<p className="mt-2 text-[9px] leading-relaxed text-slate-600">O valor completo é enviado ao backend e não volta para o navegador depois de salvo.</p></div>
  </article>;
}
